[package]
name = "adventofcode-2021"
version = "0.1.0"
authors = ["Joost van Someren <joost.v.someren@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"

